# Generated by Django 3.0.7 on 2020-06-20 09:06

from django.db import migrations


def create_basic_specialization(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    Specialization = apps.get_model('hopital', 'Specialization')
    Specialization.objects.create(title='Dantist')
    Specialization.objects.create(title='Eyeist')
    Specialization.objects.create(title='Psycho')


class Migration(migrations.Migration):
    dependencies = [
        ('hopital', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_basic_specialization, lambda x, y: None)
    ]
